# Generated by Django 5.2 on 2025-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
