# Generated by Django 5.2 on 2025-04-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_important'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLetter',
            new_name='NewsLetter',
        ),
    ]
