# Generated by Django 5.2 on 2025-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
